### ISSUE TITLE
Decode multiple classes of protobufs

### ISSUE THREAD

**Issue by kdubezerra** [trivago/logstash-codec-protobuf#3]
Right now, the codec requires its configuration to specify include path(s) and a class name. In my case, I need to send different protobufs to the same index in elasticsearch, through logstash. So, my issue is:

**Is it possible to configure the protobuf coded to decode multiple kinds of protobufs?** 

Say you have classes Unicorn and Dragon, which have different fields, but they should be stored in the same index in elasticsearch. How would you go about that? If that's not possible right now, is there any plan to implement such a feature in the codec?

**Comment by IngaFeick** [comment]
Hi! Yes and No.
Having multiple protobuf classes: yes, that's possible. But it probably doesn't do what you need.
I assume you want to read data encoded in different pb definitions from the same datasource?
That would not be possible (yet).

You can give multiple classes to the codec (see examples in the documentation) if your data is encoded in lets say definition a, which includes non primitive fields encoded in other definitions, say b and c. Then you need to provide the pathes to all of those definitions in the config. So it _does_ decode multiple kinds of protobuf, but it expects the entry point (the outermost class a) to be of the same type for all messages.

If this is not what you want then I am happy to extend the functionality. Could you maybe give some more details on your use case?

**Comment by kdubezerra** [comment]
Thanks for replying! Aha ok, so I can create an outter class/message that contains the different classes that I want, and put an oneof field for the class that I actually want to send:

```
Message Animal {
   Message Dragon {
      optional int64 age = 1;
      // dragon-specific fields
   }
   Message Unicorn {
      optional int32 age = 1;
      // unicorn-specif fields
   }
   oneof animal {
      Dragon dragon = 1;
      Unicorn unicorn = 2;
   }
}
```

So I tried this approach and the problem with it is that, if I send that to logstash, the inner class will be sent as a field, whose key is the name of the inner class. Instead of having just `{age:300}`, which is the desired behavior, I'd have something like `{unicorn: {age: 300}}` being inserted into elasticsearch. 

The use case is that, even though they are different classes, they have common fields that I'd like to query and aggregate from elasticsearch... Perhaps there's an easy way to do it despite the data being wrapped into different inner_class fields (e.g., "dragon" vs "unicorn"), but I think it might be easier to just accept different classes.

If you feel like implementing such a feature, I'll be definitely using it as soon as it's out.

**Comment by IngaFeick** [comment]
So the problem is rather with the naming / hierarchy and not the decoding itself?
The result that you describe is indeed desired behaviour with regards to your example input data. The event hierarchy matches the class layout, so that part will not change. The codec will not modify the hierarchy of the event. But what you want to achieve can easily be done with a filter modification. If I understand it correctly then you would like to just move the fields of the nested classes up one level in the event, because you cannot use them for the same aggregation in elasticsearch. For that I would recommend to add a filter like so:
    input {...}
    filter {
      if [dragon] {
        mutate { rename => { "[dragon][age]" => "age" } }
      }
      else if [unicorn] {
        mutate { rename => { "[unicorn][age]" => "age" } }
      }
    }
That way you'll always have a field called "age" on the topmost event level that you can aggregate on, no matter if its data comes from a unicorn subfield or a dragon.
Let me know if I misunderstood your use case or the code doesn't work (didn't have time to test it yet tbh). Cheers!

**Comment by kdubezerra** [comment]
So that means having such a rule for every field of every inner class? Perhaps there are better solutions for this, no? Anyway, if the multiple classes functionality is implemented, let me know :)

**Comment by IngaFeick** [comment]
Hi again :)
Well, I understand that it might look tedious to you, but I think it is the cleanest solution. From my point of view, the duty of an input plugin / codec is to restore the encoding of and deliver the input data, and nothing but. I dont think an input codec is a good place to do any kind of data transformation. And what you are aiming for is just that: you want to alter the hierarchy of the documents that you feed to logstash. So in my opinion the only right place to do this is some kind of filter. There might be better ones than the one suggested by me. Maybe there is a nice filter already out there which lets you do this comfortable. Either way, it's outside of the scope of this plugin so I'm sorry, I will not be able to help you there.

**Comment by kdubezerra** [comment]
Oh I think the filter you provided is exactly what is needed in my use case! By "better solutions", I meant supporting multiple protobufs in the same codec. But of course, if you as the developer of the plugin think that this feature does not make sense to be added, that is reason enough to close this issue.
